version: "3.5"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: rmi_nextjs
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
    command: "yarn start"
