- hosts: appservers
  vars:
    deploy_to: /data/docker-data/2020.responsibleminingindex.org/front
    deploy_user: antistatique
    deploy_group: antistatique

  roles:
    - { role: capistrano, become: yes }
